version: "3.8"

services:
  postgres-auth:
    image: postgres
    container_name: pg-db-auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 452389
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - forum-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M

  mongo-user:
    image: mongo:latest
    container_name: mongo-db-user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user
      MONGO_INITDB_ROOT_USERNAME: 'vitaliy'
      MONGO_INITDB_ROOT_PASSWORD: '452389'
    volumes:
      - mongo-data:/data
    networks:
      - forum-net

networks:
  forum-net:
    driver: bridge

volumes:
  pg-data:
  mongo-data: