input {
    tcp {
        port => 50000
        codec => json_lines
    }
}

filter {

    json {
        source => "message"
        target => "tempMsg"
        add_tag => "parsed"
    }

    if "parsed" in [tags] {
        mutate {
            add_field => {
                "serviceId" => "%{[tempMsg][serviceId]}"
                "serviceLogger" => "%{[tempMsg][logger]}"
                "metadata" => "%{[tempMsg][metadata]}"
                "msg" => "%{[tempMsg][message]}"
            }
        }

        date {
            match => ["[tempMsg][timestamp]", "yyyy-MM-dd'T'HH:mm:ss"]
            target => "time"
        }

    }
    mutate {
        remove_field => [
            "tempMsg"
        ]
    }
}

output {
    elasticsearch {
        index => "logs-%{+YYYY.MM.dd}"
        hosts => "${ELASTIC_HOSTS}"
        user => "${ELASTIC_USER}"
        password => "${ELASTIC_PASSWORD}"
        cacert => "certs/ca/ca.crt"
    }
}